---
openapi: 3.0.0
info:
  title: Voltapp API
  description: Voltap API draft
  termsOfService: http://swagger.io/terms/
  contact:
    name: Antonios Antoniou, Polydoros Giannouris, Efthimios Grigorakis, Anestis Kaimakamidis
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.2.0
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/voltapp/voltapp/1.2.0
- url: https://virtserver.swaggerhub.com/eegrigor/voltapp/1.0
  description: SwaggerHub API Auto Mocking
- url: https://b98f878f-7158-420f-8470-0ad12c0a2a68.mock.pstmn.io
paths:
  /user:
    get:
      description: |
        Get all users
      operationId: getUsers
      parameters:
      - name: tags
        in: query
        description: filter users
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: limit
        in: query
        description: how many users are returned
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{id}/sight:
    get:
      description: FR7 - View my sight wishlist
      operationId: viewWishlist
      parameters:
      - name: id
        in: path
        description: id of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: View wishlist successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sight'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                    
  /user/{user-id}/sight/{sight-id}:
    put:
      description: FR3 - Add a sight to my wishlist
      operationId: addSight
      parameters:
      - name: user-id
        in: path
        description: user that adds the sight
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: sight-id
        in: path
        description: user that adds the sight
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64          
      requestBody:
        description: Sight to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSight'
        required: true
      responses:
        "200":
          description: sight added
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: FR4 - Delete  sight from my wishlist
      operationId: deleteSight
      parameters:
      - name: user-id
        in: path
        description: id of ther user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: sight-id
        in: path
        description: wishlist id of the sight we want to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: delete success
          content:
            application/json:
              schema:
                type: object # return user and sight id
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
  /user/{id}/tour:
    get:
      description: FR8 - View my tour list
      operationId: viewTours
      parameters:
      - name: id
        in: path
        description: id of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: View tour list successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tour'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/{id}/tour/{tour-id}:
    post:
      description: FR5 - Join a tour
      operationId: joinTour
      parameters:
      - name: id
        in: path
        description: id of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tour-id
        in: path
        description: id of the tour
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Tour to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTour'
        required: true
      responses:
        "200":
          description: joined the tour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: FR6 - Leave a tour
      operationId: leaveTour
      parameters:
      - name: id
        in: path
        description: id of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tour-id
        in: path
        description: id of the tour
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Left tour successfully
          content:
            application/json:
              schema:
                type: object # return user and tour id
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tourguide/{userID}:
    post:
      description: FR12 - Add a user to the tour guide database
      operationId: changeRole
      parameters:
      - name: userID
        in: path
        description: the userID that's added to the database of tour guides
        required: true
        style: simple
        schema:
          type: string
      responses:
        "200":
          description: Successfully changed user role
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      description: Needed to know if a user is authorized to be a tour guide
      operationId: isTourGuide
      parameters: 
      - name: userID
        in: path
        required: true
        style: simple
        schema:
          type: string
      responses:
        "200":
          description: User is also a tour guide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tourguide'
        default:
          description: User is not a tour guide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tourguide/{tourguideId}/tour:
    post:
      description: FR9 - Create a tour
      operationId: createTour
      parameters:
      - name: tourguideId
        in: path
        description: tourguide that creates the tour
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Tour to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tour'
        required: true
      responses:
        "200":
          description: tour created
          content:
            application/json:
              schema:
                type: integer
                format: int64 # return the tour id
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tourguide/{tourguideId}/tour/{tourId}:
    put:
      description: FR10 - Edit a tour
      operationId: editTour
      parameters:
      - name: tourguideId
        in: path
        description: Î¤ourguide that edits the tour
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tourId
        in: path
        description: tour that is editted
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Tour to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditTour'
        required: true
      responses:
        "200":
          description: tour created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: FR11 - Cancel a tour
      operationId: cancelTour
      parameters:
      - name: tourguideId
        in: path
        description: id of the tourguide
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tourId
        in: path
        description: tour that is canceled
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Cancel tour successfully
          content:
            application/json:
              schema:
                type: integer
                format: int64 # return the tour id
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      required:
      - id
      - username
      - password
      - birthdate
      - email
      - firstname
      - surname
      - tours
      - toursattended
      - wishlist
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        birthdate:
          type: array
          items:
            type: integer
            format: int32
        firstname:
          type: string
        surname:
          type: string
        address:
          type: string
        wishlist:
          type: array
          items:
            type: object
        tours:
          type: array
          items:
            type: object
        toursattented:
          type: integer
          format: int32
    Tourguide:
      allOf:
      - $ref: '#/components/schemas/User'
      - required:
        - tourstohost
        type: object
        properties:
          tourstohost:
            type: array
            items:
              type: object
    Guest:
      required:
      - userId
      type: object
      properties:
        userId:
          type: integer
          format: int64
    NewSight:
      required:
      - name
      - fromDate
      - toDate
      type: object
      properties:
        name:
          type: string
        fromDate:
          type: object
        toDate:
          type: object 
    Sight:
      required:
      - sightId
      - sightname
      - availableTours
      - sightlocation
      type: object
      properties:
        sightId: 
          type: integer
          format: int64
        sightname:
          type: string
        sightlocation:
          type: object
        availableTours:
          type: array
          items:
            type: object   
    NewTour:
      required:
      - sightId
    EditTour:
      required:
      - newDate
      - newFromTime
      - newToTime
      - newMaxParticipants
      type: object
      properties:
        newDate:
          type: object # (#/components/schemas/Date)
        newFromTime:
          type: integer
          format: int32
        newToTime:
          type: integer
          format: int32  
        newMaxParticipants:
          type: integer
          format: int32
    Tour:
      required:
      - date
      - maxparticipants
      - participants
      - sight
      - fromtime
      - toTime
      - tourId
      - tourguide
      type: object
      properties:
        sight:
          type: object
        date:
          type: array
          items:
            $ref: '#/components/schemas/Date'
        fromtime:
          type: integer
          format: int32
        toTime:
          type: integer
          format: int32
        tourId:
          type: integer
          format: int64
        maxparticipants:
          type: integer
          format: int32
        participants: # participants and tour guide returned as userId's
          type: array
          items:
            $ref: '#/components/schemas/User'
        tourguide:
          type: string
    Date:
      required:
      - year
      - month
      - day
      type: object
      properties:
        year:
          type: integer
          format: int32
        month:
          type: integer
          format: integer
        day:
          type: integer
          format: int32
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string